version: '3.8'

services:

  redis:
    image: redis:7
    container_name: concert-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

  postgres:
    image: postgres:17
    container_name: concert-postgres
    environment:
      POSTGRES_USER: skala
      POSTGRES_PASSWORD: skala1229
      POSTGRES_DB: concert
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: concert-nginx
    ports:
      - "8080:8080"
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - redis
      - postgres

volumes:
  postgres-data: